name       : x264
version    : 0.164.3095
release    : 18
source     :
    # Note for packagers: must be updated to the latest commits on 'stable' branch.
    - git|https://code.videolan.org/videolan/x264.git : baee400fa9ced6f5481a728138fed6e867b0ff7f
license    : GPL-2.0-or-later
component  : multimedia.codecs
summary    : A library for encoding video streams into the H.264/MPEG-4 AVC format.
description: |
    A library for encoding video streams into the H.264/MPEG-4 AVC format.
optimize   :
    - no-symbolic
    - no-bind-now
setup      : |
    %configure \
        --enable-lto \
        --enable-pic \
        --enable-shared \
        --system-libx264
build      : |
    %make
install    : |
    %make_install
