name       : x264
version    : '20180503'
release    : 6
source     :
    - http://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20180503-2245.tar.bz2 : b62f6fe49b525640fdc22a6ffcb1a1d002469a9df4e8b8f027e23cc0ea104b27
license    : GPL-2.0
component  : multimedia.codecs
summary    : A library for encoding video streams into the H.264/MPEG-4 AVC format.
description: |
    A library for encoding video streams into the H.264/MPEG-4 AVC format.
builddeps  :
    - yasm
optimize   :
    - no-symbolic
    - no-bind-now
setup      : |
    %configure --enable-shared \
               --disable-cli \
               --enable-pic \
               --enable-debug \
               --enable-lto
build      : |
    %make
install    : |
    %make_install
