name       : x264
version    : 0.161.3020
release    : 11
source     :
    # Note for packagers: must be updated to the latest commits on 'stable' branch.
    - git|https://code.videolan.org/videolan/x264.git  : d198931a63049db1f2c92d96c34904c69fde8117
license    : GPL-2.0-or-later
component  : multimedia.codecs
summary    : A library for encoding video streams into the H.264/MPEG-4 AVC format.
description: |
    A library for encoding video streams into the H.264/MPEG-4 AVC format.
optimize   :
    - no-symbolic
    - no-bind-now
setup      : |
    %configure \
        --enable-lto \
        --enable-pic \
        --enable-shared \
        --system-libx264
build      : |
    %make
install    : |
    %make_install
