name       : x264
version    : '20180119.2245'
release    : 5
source     :
    - http://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20180119-2245-stable.tar.bz2 : 32b54ad52ee29c82be3882b8907d0177832ec0aaa78210dd88f46784f771b04f
license    : GPL-2.0
component  : multimedia.codecs
summary    : A library for encoding video streams into the H.264/MPEG-4 AVC format.
description: |
    A library for encoding video streams into the H.264/MPEG-4 AVC format.
builddeps  :
    - yasm
setup      : |
    %configure --enable-shared --disable-cli --disable-asm
build      : |
    %make
install    : |
    %make_install
