name       : x264
version    : 0.159.2999
release    : 9
source     :
    # Note for packagers: must be updated to the latest commits on 'stable' branch.
    - git|https://code.videolan.org/videolan/x264.git  : 296494a4011f58f32adc54304a2654627558c59a
license    : GPL-2.0-or-later
component  : multimedia.codecs
summary    : A library for encoding video streams into the H.264/MPEG-4 AVC format.
description: |
    A library for encoding video streams into the H.264/MPEG-4 AVC format.
optimize   :
    - no-symbolic
    - no-bind-now
setup      : |
    %configure \
        --enable-lto \
        --enable-pic \
        --enable-shared \
        --system-libx264
build      : |
    %make
install    : |
    %make_install
