name        : x264
version     : 20141218.2245
release     : 2
source     :
    - http://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20141218-2245-stable.tar.bz2 : 3519e8fa3399845c7d2248d0a7297a923ac6bdc78d0ec15e85026e810670e1be
license     :
    - GPLv2+
summary     : A library for encoding video streams into the H.264/MPEG-4 AVC format.
builddeps   :
    - yasm
description : |
    A library for encoding video streams into the H.264/MPEG-4 AVC format.n
setup      : |
    %configure --enable-shared --disable-cli
build      : |
    %make
install    : |
    %make_install
