name       : x264
version    : 20170411.2245
release    : 3
source     :
    - http://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20170411-2245-stable.tar.bz2 : 6edeb05b8f659adf32b3af7b3ae25958a8192bd2d09ef853e38caa02149d3927
license    :
    - GPL-2.0
summary    : A library for encoding video streams into the H.264/MPEG-4 AVC format.
component  : multimedia.codecs
builddeps  :
    - yasm
description: |
    A library for encoding video streams into the H.264/MPEG-4 AVC format.n
setup      : |
    %configure --enable-shared --disable-cli
build      : |
    %make
install    : |
    %make_install
