name       : x264
version    : '20191013.2245'
release    : 8
source     :
    - http://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20191013-2245-stable.tar.bz2 : 3f20306c4d8bd3b5805f55bcaca6614544a9896740dd84e13d0501edb9b25a9b
license    : GPL-2.0-or-later
component  : multimedia.codecs
summary    : A library for encoding video streams into the H.264/MPEG-4 AVC format.
description: |
    A library for encoding video streams into the H.264/MPEG-4 AVC format.
builddeps  :
    - yasm
optimize   :
    - no-symbolic
    - no-bind-now
setup      : |
    %configure --enable-shared \
               --enable-pic \
               --enable-debug \
               --enable-lto
build      : |
    %make
install    : |
    %make_install
