name       : x264
version    : 0.161.3049
release    : 13
source     :
    # Note for packagers: must be updated to the latest commits on 'stable' branch.
    - git|https://code.videolan.org/videolan/x264.git  : 55d517bc4569272a2c9a367a4106c234aba2ffbc
license    : GPL-2.0-or-later
component  : multimedia.codecs
summary    : A library for encoding video streams into the H.264/MPEG-4 AVC format.
description: |
    A library for encoding video streams into the H.264/MPEG-4 AVC format.
optimize   :
    - no-symbolic
    - no-bind-now
setup      : |
    %configure \
        --enable-lto \
        --enable-pic \
        --enable-shared \
        --system-libx264
build      : |
    %make
install    : |
    %make_install
